@echo off
call trademe-cli add -t "Antique Vase" -d "This exquisite antique porcelain vase is a true masterpiece, dating back to the early 1900s. It features intricate floral patterns in vibrant colors, making it a stunning addition to any collector’s display. The vase has been carefully preserved over the years, showcasing the beauty of its craftsmanship. The delicate design, coupled with the smooth, glossy finish, highlights the skill of the artisan who created it. The flowers depicted on the vase are hand-painted, and the colors—rich reds, deep blues, and soft greens—are still as vibrant as the day they were applied. The intricate detailing around the rim and base of the vase speaks to the attention to detail given during its creation. This vase is not only a work of art, but it also represents the craftsmanship and artistic vision of the era in which it was created. It stands at approximately 12 inches tall, making it a perfect size to be displayed as a statement piece in any home, office, or collection. Despite its age, the vase remains in remarkable condition, with no visible cracks or chips. Its vintage nature and historical significance make it a rare and valuable piece for collectors of fine antiques. Whether you are an avid collector of porcelain or simply someone who appreciates the beauty of hand-crafted items, this vase is sure to be a prized addition to your collection. Its timeless beauty ensures that it will remain an elegant and cherished item for many years to come." -s 150.00
timeout /t 1
call trademe-cli add -t "Modern Art Painting" -d "This contemporary abstract painting captures the essence of modern artistry with its bold brushstrokes and vivid colors. The piece is large, measuring 48x36 inches, and is painted on a high-quality canvas. The artist utilizes dynamic and fluid strokes of paint, intertwining shades of red, blue, and gold to evoke a sense of movement and emotion. The composition of the painting creates a captivating visual experience, with layers of colors bleeding into one another and shifting in hue. The contrasts in the painting draw the eye and provoke a deep emotional response. It is an exploration of color, texture, and form, with a balance of chaos and calm that is characteristic of abstract expressionism. The painting is framed in a sleek, minimalist black frame that complements the boldness of the artwork. Its modern style makes it a perfect fit for contemporary homes or galleries, and it is sure to be a conversation starter. Whether you are an art enthusiast or a seasoned collector, this piece would be a valuable addition to any collection. The artist's unique approach to color and texture brings a fresh perspective to abstract art, ensuring that it will be admired for years to come." -s 450.00
timeout /t 1
call trademe-cli add -t "Classic Vinyl Records" -d "A collection of classic vinyl records from the 1960s and 1970s, featuring albums from legendary artists such as The Beatles, Led Zeppelin, Jimi Hendrix, and more. These records have been meticulously cared for, ensuring that each one is in excellent condition. The albums are housed in their original covers, which are still vibrant and well-preserved. Vinyl records offer a unique listening experience, with warm, rich sound that digital formats simply cannot replicate. Each album in this collection holds a piece of music history, capturing the essence of an era defined by musical revolution and cultural change. The collection includes iconic albums like ‘Abbey Road’ by The Beatles, ‘Led Zeppelin IV’ by Led Zeppelin, and ‘Are You Experienced’ by Jimi Hendrix. These timeless records are perfect for collectors, music lovers, or anyone looking to experience the magic of vinyl. Whether you are adding to your existing collection or just starting, this set of records will be a valuable addition to your home or studio. The albums are tested and sound great, delivering the authentic, analog sound that made vinyl records so beloved. This is a rare opportunity to own a piece of music history and enjoy the nostalgia that comes with it." -s 200.00
timeout /t 1
call trademe-cli add -t "Mid-Century Modern Chair" -d "This mid-century modern chair is a design classic, built to combine both form and function. The chair features clean, minimalist lines and is made from solid wood, giving it a sturdy and elegant frame. The seat is upholstered in a rich, neutral-toned fabric that complements its timeless design. The ergonomic shape provides comfort and support, making it not only a stylish piece but also a practical addition to any living room, office, or study. The chair’s smooth wooden legs and sleek backrest evoke the beauty of mid-century design, with a touch of Scandinavian influence. Its simple yet sophisticated aesthetic is perfect for anyone looking to create a chic, minimalist living space or for those who appreciate the refined craftsmanship of mid-century furniture. The chair is in excellent condition, having been restored to preserve its original charm and quality. It offers a perfect balance between comfort, durability, and style. Whether used as an accent piece or a functional chair for daily use, this mid-century modern chair will add a touch of elegance and history to any room." -s 250.00
timeout /t 1
call trademe-cli add -t "Antique Pocket Watch" -d "An exquisite antique pocket watch from the early 1900s, this piece is a fine example of craftsmanship from a bygone era. The watch features intricate engravings on its silver case, with delicate floral and geometric patterns that showcase the artistry of its maker. The dial is a pristine white with Roman numerals, and the minute and hour hands are beautifully detailed, still working perfectly to keep accurate time. The watch is wound via a traditional key mechanism, offering a charmingly nostalgic experience for collectors or watch enthusiasts. This timepiece is not only a functional object, but it also serves as a beautiful collectible, capturing the elegance and craftsmanship of the past. The case is in excellent condition, with no visible damage or wear, making it a perfect item for display or for use as a unique timekeeping accessory. Whether you’re a lover of vintage watches, a collector of antique timepieces, or someone who appreciates fine craftsmanship, this pocket watch is sure to become a cherished addition to your collection." -s 350.00
timeout /t 1
call trademe-cli add -t "Handmade Leather Wallet" -d "This luxurious handmade leather wallet is a testament to the quality and skill of its craftsman. Made from premium, vegetable-tanned leather, the wallet is designed to age beautifully, developing a rich patina over time. The wallet features multiple card slots, a coin pocket, and a spacious bill compartment, allowing for efficient organization of your essentials. The stitching is meticulously done by hand, ensuring durability and a refined finish. The design is minimalist yet elegant, with a smooth, polished leather exterior that exudes sophistication. The wallet’s sleek design makes it a perfect accessory for both casual and formal occasions, while the high-quality leather ensures that it will last for many years. It’s not just a wallet, but an investment in craftsmanship and style. Whether you’re treating yourself or looking for a thoughtful gift for someone special, this handmade leather wallet is a timeless accessory that will only improve with age." -s 75.00
timeout /t 1
call trademe-cli add -t "Vintage Typewriter" -d "This vintage typewriter, dating back to the 1950s, is a beautifully restored piece of history. Featuring a sturdy metal body and classic typewriter keys, the machine has been carefully maintained to ensure it remains fully functional. The smooth operation of the keys and the satisfying ‘click-clack’ sound they make is a nostalgic experience for anyone who appreciates the beauty of old-school technology. The typewriter is in excellent condition, with minimal wear to the keys and a clean, well-preserved frame. It makes for a great collector's item or a functional tool for writers and typists looking to experience a vintage writing experience. The typewriter's classic design and durable construction ensure that it will last for many more years of use. The simplicity and craftsmanship behind the typewriter are what make it a cherished item for those who value the nostalgia and functionality of vintage equipment." -s 200.00
timeout /t 1
call trademe-cli add -t "Vintage Leather Jacket" -d "This genuine vintage leather jacket, dating back to the 1980s, has been carefully preserved and is in excellent condition. The supple leather has a beautiful patina, adding character and warmth to the jacket’s overall look. The jacket features classic biker-style detailing, including a zippered front, adjustable cuffs, and multiple pockets for practicality. Its bold, timeless style makes it a perfect fit for both casual and edgy fashion statements. The jacket is fully lined, ensuring comfort during wear while providing warmth on cooler days. It is designed to fit comfortably, offering a flattering silhouette with enough room for layering underneath. Whether you are a collector of vintage clothing or simply looking for a high-quality, stylish jacket, this piece will be a valuable addition to your wardrobe. The jacket’s durability, timeless appeal, and authentic vintage charm make it a sought-after item for fashion enthusiasts and collectors alike." -s 180.00
timeout /t 1
call trademe-cli add -t "Vintage Record Player" -d "This vintage record player from the 1960s offers an authentic audio experience with its rich, warm sound and retro design. The player is fully functional, with a working turntable and needle, making it a perfect addition for audiophiles or collectors of vintage electronics. The body of the player is made from sturdy wood, with a polished finish that highlights the natural grain. The speakers are built into the design, providing a compact but powerful listening experience. This record player has been carefully serviced to ensure it operates perfectly and will continue to provide years of enjoyment. Whether you are a fan of classic vinyl records or simply appreciate the craftsmanship of vintage electronics, this record player will add a nostalgic touch to any home." -s 220.00
timeout /t 1
call trademe-cli add -t "Antique Chess Set" -d "This exquisite antique chess set is a rare find, with finely carved wooden pieces that date back to the early 1900s. The set includes beautifully crafted kings, queens, bishops, knights, rooks, and pawns, all hand-carved from high-quality wood. The chessboard itself is made from rich, dark wood, with alternating light and dark squares that highlight the craftsmanship of its maker. Each piece has been meticulously hand-painted with gold and silver accents, adding an extra layer of elegance. The set is in excellent condition, with no visible damage or wear, making it an ideal addition to any collector’s display. Whether you are a chess enthusiast, a history lover, or someone who appreciates fine craftsmanship, this antique chess set is sure to become a prized possession." -s 300.00
timeout /t 1
call trademe-cli add -t "Luxury Fountain Pen" -d "This luxury fountain pen is an exquisite writing instrument that combines precision, beauty, and functionality. Made from high-quality materials, including a polished stainless steel nib and a finely crafted resin body, the pen is a pleasure to write with. The pen’s elegant design features intricate engravings and a sleek, modern aesthetic, making it a perfect accessory for any professional or collector. It writes smoothly, ensuring a flawless writing experience whether you’re jotting down notes or signing important documents. The pen is designed for use with refillable ink cartridges, offering convenience and sustainability. Whether you’re a writing enthusiast, a professional, or someone who appreciates the art of fine writing instruments, this luxury fountain pen is an investment in both style and functionality." -s 120.00
timeout /t 1
call trademe-cli add -t "Handcrafted Wooden Sculpture" -d "This stunning handcrafted wooden sculpture showcases the skill and artistry of its maker. The piece is carved from a single piece of premium hardwood, with intricate detailing that highlights the natural grain of the wood. The design is abstract, yet evokes a sense of movement and emotion, capturing the beauty of the material and the artist’s vision. The sculpture stands at 18 inches tall, making it a striking centerpiece for any home or office. Its smooth finish and unique design make it a conversation starter and a beautiful addition to any collection. Whether you are a collector of fine art or simply appreciate craftsmanship, this handcrafted wooden sculpture is sure to be a cherished piece for years to come." -s 400.00
timeout /t 1
call trademe-cli add -t "Vintage Guitar" -d "This vintage guitar, dating back to the 1960s, offers the rich, warm sound that only comes from years of use and expert craftsmanship. The guitar features a classic design, with a beautiful sunburst finish on its wooden body, and a sleek, smooth neck. The fretboard is made from high-quality rosewood, providing a comfortable playing experience. The pickups and electronics have been carefully restored to ensure the guitar still sounds as good as it did when it was first made. The guitar is perfect for collectors, musicians, or anyone who appreciates the unique tone and history of a vintage instrument. Whether you are a player looking for a quality instrument or a collector seeking a rare find, this vintage guitar will make a valuable addition to any collection." -s 550.00
timeout /t 1
call trademe-cli add -t "Custom Handmade Knife" -d "This custom handmade knife is a work of art, crafted by a skilled artisan using high-quality stainless steel and a hand-carved wooden handle. The blade is meticulously forged to ensure sharpness and durability, while the handle is ergonomically designed for a comfortable grip. The knife features intricate engravings along the blade and handle, showcasing the craftsmanship of the maker. Whether you are an avid outdoorsman, a collector of fine tools, or someone who appreciates quality craftsmanship, this knife is a must-have for your collection." -s 300.00
timeout /t 1
call trademe-cli add -t "Vintage Camera" -d "This vintage camera, made in the 1950s, is a classic piece of photography equipment. The camera is fully functional, with a crisp lens and smooth shutter mechanism, capturing images with the precision of its original design. The body is made from durable metal and features a timeless design that any photography enthusiast will appreciate. It comes with the original leather case and manual, making it a great addition to any vintage camera collection. Experience the charm of analog photography with this beautifully crafted camera." -s 180.00
timeout /t 1
call trademe-cli add -t "Luxury Silk Scarf" -d "This luxury silk scarf is a high-end accessory that adds sophistication and elegance to any outfit. Made from the finest silk, the scarf feels soft and smooth against the skin, while the vibrant colors and intricate patterns add a touch of class. Whether you wear it around your neck or drape it over your shoulders, this scarf will elevate your style. The silk’s natural sheen gives the scarf a luxurious appearance, making it a perfect gift for someone special or a stunning addition to your own wardrobe." -s 120.00
timeout /t 1
call trademe-cli add -t "Handmade Pottery Bowl" -d "This handmade pottery bowl is a unique piece, carefully crafted by a local artisan. The bowl features beautiful, hand-painted designs that add character and charm. The glaze is applied in layers, creating a rich, textured finish that highlights the natural imperfections of the clay. This bowl is perfect for serving food or as a decorative piece. Its rustic design and sturdy construction make it a functional yet artistic addition to any home." -s 80.00
timeout /t 1
call trademe-cli add -t "Antique Writing Desk" -d "This antique writing desk is a beautiful example of classic craftsmanship. Made from high-quality wood, the desk features intricate carvings and elegant detailing that make it a standout piece in any room. The spacious surface provides ample room for writing or working, while the multiple drawers offer plenty of storage space for papers and supplies. This desk would make an excellent addition to a home office or study, blending functionality with timeless beauty." -s 350.00
timeout /t 1
call trademe-cli add -t "Vintage Suitcase" -d "This vintage suitcase from the 1930s features sturdy leather straps and a durable exterior, perfect for collectors of retro travel gear. The suitcase is still in great condition, with a few minor signs of wear that add character to its timeless design. The interior is lined with soft fabric, ensuring your belongings are protected during travel. This suitcase makes a great display piece for your home or a functional item for those who appreciate the charm of vintage luggage." -s 150.00
timeout /t 1
call trademe-cli add -t "Custom Wooden Coffee Table" -d "This custom-made wooden coffee table is crafted from premium hardwood, designed to be both stylish and functional. The table features a sleek, minimalist design with clean lines, making it an ideal fit for modern homes or apartments. The smooth finish of the wood highlights the natural grain, adding texture and character. This coffee table offers a spacious surface for drinks, books, or decorative items, and its sturdy construction ensures it will last for years to come." -s 225.00
timeout /t 1
call trademe-cli add -t "Vintage Radio" -d "This vintage radio from the 1950s combines retro style with classic functionality. The wooden body has a polished finish, with chrome accents adding a touch of elegance. The radio works perfectly, with clear sound and an intuitive dial for tuning into your favorite stations. This radio is a great collector’s item, offering both nostalgia and quality craftsmanship. It’s the perfect addition for those who appreciate vintage electronics or unique home décor." -s 100.00
timeout /t 1
call trademe-cli add -t "Handmade Wooden Guitar" -d "This handmade wooden guitar is crafted with care and precision, designed for both musicians and collectors. The guitar features a solid wood body with beautiful grain patterns, and the fretboard is made of smooth rosewood for comfortable playability. The instrument is finely tuned, producing rich, vibrant sound. This guitar is perfect for both beginners and experienced musicians, offering a high-quality, affordable alternative to mass-produced instruments." -s 400.00
timeout /t 1
call trademe-cli add -t "Crystal Decanter Set" -d "This elegant crystal decanter set includes a beautifully crafted decanter and matching glasses, perfect for serving whiskey, wine, or other fine spirits. The decanter is made from high-quality crystal, featuring intricate etchings that catch the light beautifully. The matching glasses are also made from crystal and have a similar etched design. This set makes a perfect gift for collectors of fine glassware or anyone looking to add a touch of luxury to their bar or dining area." -s 150.00
timeout /t 1
call trademe-cli add -t "Vintage Bar Cart" -d "This vintage bar cart is a charming and functional piece of furniture that adds sophistication to any room. The cart features two tiers of storage space for bottles, glassware, and accessories, with an elegant metal frame and wooden shelves. The smooth wheels allow for easy mobility, making it perfect for entertaining guests. The classic design, combined with its practical functionality, makes it a must-have for those who love to entertain in style." -s 250.00
timeout /t 1
call trademe-cli add -t "Antique Floor Lamp" -d "This antique floor lamp from the 1920s features an ornate design with detailed metalwork and a beautiful fabric shade. The lamp has been fully restored to preserve its vintage charm, and it provides soft, warm lighting, making it an ideal piece for living rooms, bedrooms, or study areas. The elegant design and rich finish of the lamp make it a striking focal point in any room. Whether you are a collector or simply love vintage home décor, this lamp is a wonderful addition to any space." -s 120.00
timeout /t 1
call trademe-cli add -t "Retro Coffee Maker" -d "This retro coffee maker combines classic style with modern functionality. Featuring a stainless steel body and a sleek, vintage-inspired design, the coffee maker brews rich, aromatic coffee at the touch of a button. The easy-to-use controls and compact size make it perfect for small kitchens or offices. Whether you’re a coffee aficionado or someone who appreciates vintage appliances, this coffee maker will make a stylish and practical addition to your home." -s 90.00
timeout /t 1
call trademe-cli add -t "Antique Gold Watch" -d "This antique gold watch is a luxurious and timeless accessory. Made from 18-karat gold, the watch features a classic round face with Roman numerals and an elegant leather band. The watch has been carefully restored to ensure it keeps accurate time, and it’s in excellent condition with minimal signs of wear. This watch is a perfect investment for collectors or anyone who appreciates fine jewelry and vintage accessories." -s 500.00
timeout /t 1
call trademe-cli add -t "Handcrafted Wooden Bench" -d "This handcrafted wooden bench is built from premium oak wood, offering a rustic yet elegant design. The smooth, natural finish of the wood highlights its grain and texture, giving the bench a warm, earthy appeal. The sturdy construction ensures it will last for many years, whether used indoors or outdoors. This versatile bench works well as extra seating in living rooms, entryways, or patios, and its timeless style makes it a valuable addition to any space." -s 250.00
timeout /t 1
call trademe-cli add -t "Antique Silverware Set" -d "This antique silverware set is a rare and elegant collection of utensils dating back to the early 1900s. The set includes knives, forks, spoons, and serving pieces, all made from high-quality silver. Each piece is beautifully engraved with intricate patterns, showcasing the fine craftsmanship of the time. The silverware is in excellent condition, and it makes a perfect addition to any collector’s display or an ideal set for those who appreciate the beauty and history of vintage tableware." -s 350.00
timeout /t 1
call trademe-cli add -t "Vintage Tennis Racket" -d "This vintage tennis racket, made in the 1960s, is a classic example of craftsmanship and design. The racket features a wooden frame with a unique, hand-woven string pattern. Despite its age, the racket is in excellent condition and could be used for display or even for actual play. Its vintage appeal and the quality of the materials used make it a desirable item for tennis enthusiasts or collectors of sports memorabilia." -s 120.00
timeout /t 1
call trademe-cli add -t "Antique Oil Lamp" -d "This antique oil lamp from the early 1900s is a charming piece that brings a touch of nostalgia and elegance to any home. The lamp features a beautifully detailed brass base and a delicate glass reservoir, perfect for creating a soft, ambient glow. The lamp has been carefully restored to ensure it is fully functional, providing the perfect lighting for cozy evenings or as a unique decorative piece. Whether you are a lover of vintage lighting or a collector of antique items, this oil lamp is sure to become a treasured addition to your home." -s 95.00
timeout /t 1
call trademe-cli add -t "Vintage Chess Board" -d "This vintage chess board, crafted from high-quality wood, features alternating dark and light squares with detailed inlays. The board is large, providing ample space for play, and its classic design makes it a great addition to any home or office. The intricate woodwork and the aged finish of the board give it a timeless appeal, making it a prized possession for chess enthusiasts and collectors alike. This chess board can also serve as a display piece for those who appreciate fine craftsmanship." -s 130.00
timeout /t 1
call trademe-cli add -t "Handwoven Wool Rug" -d "This handwoven wool rug is a stunning piece that adds warmth and character to any room. The rug features intricate patterns, handwoven by skilled artisans using traditional techniques. The rich colors and soft wool make the rug not only beautiful but also durable and comfortable. Its timeless design complements a variety of décor styles, making it a versatile addition to any space. Whether placed in a living room, bedroom, or hallway, this rug will instantly elevate the look and feel of your home." -s 200.00
timeout /t 1
call trademe-cli add -t "Antique Table Clock" -d "This antique table clock is an elegant timepiece from the 19th century, featuring a brass casing with intricate engravings. The clock's classic design includes Roman numerals and a delicate clock face, adding a touch of sophistication to any mantel or desk. The clock is fully functional, keeping accurate time, and has been carefully maintained to preserve its beauty and historical value. This clock is a perfect addition for collectors or anyone who appreciates vintage timepieces." -s 300.00
timeout /t 1
call trademe-cli add -t "Handcrafted Leather Belt" -d "This handcrafted leather belt is made from high-quality, vegetable-tanned leather, which develops a rich patina over time. The belt features a sturdy brass buckle and is meticulously stitched by hand, ensuring both durability and style. The sleek, minimalist design makes it a versatile accessory that pairs well with both casual and formal outfits. This belt is not only a functional wardrobe essential but also a timeless piece that improves with age." -s 70.00
timeout /t 1
call trademe-cli add -t "Antique Iron Door Knob" -d "This antique iron door knob is a beautifully crafted piece that adds a touch of vintage charm to any door. The knob features intricate detailing and a sturdy metal construction, ensuring it will last for many years. Its timeless design complements a variety of home styles, from traditional to rustic. Whether you are restoring an old home or looking to add character to a new space, this antique door knob is a unique and functional piece of history." -s 50.00
timeout /t 1
